import numpy as np
from typing import Dict, List, Any
from collections import defaultdict

from magi.physical.constants import CW_TASK_SEQUENCE, MW_TASK_SEQUENCE, PHYSIO_CTRL_HR
from magi.digital.config import ConfigState
from magi.digital.models import TaskRecord, PhysioRecord

#  SECTION 8 — KPI COMPUTATION ENGINE
# ─────────────────────────────────────────────────────────────────────────────

class KPIComputer:
    """
    Computes the full KPI suite from a completed simulation run's event logs.

    KPIs are grouped into three categories aligned with the MAGI framework's
    measurement objectives:

    Operational KPIs
        Standard production efficiency metrics (throughput, cycle time,
        utilisation, buffer wait).

    Physiological / Ergonomic KPIs
        Metrics directly related to worker wellbeing, as mandated by the
        Industry 5.0 human-centric paradigm. The Physiological Load Index
        (PLI) is computed as the area under the HR curve above the worker's
        resting (CTRL) baseline — a well-established occupational ergonomics
        metric (Kilbom, 1990).

    Lean KPIs
        Overall Equipment Effectiveness (OEE) proxy, line balance ratio,
        and takt adherence — the standard Industry 4.0 lean manufacturing
        KPI suite.
    """

    def compute(
        self,
        task_log:       List[TaskRecord],
        physio_log:     List[PhysioRecord],
        config:         ConfigState,
        duration_hours: float,
        cw_busy_time:   List[float],
        mw_busy_time:   List[float],
        robot_busy:     List[float],
        generated:      int,
        dropped:        int,
    ) -> Dict[str, Any]:
        """
        Compute all KPIs and return as a flat dict.

        Args:
            task_log:       All TaskRecord objects from the simulation run.
            physio_log:     All PhysioRecord objects from the simulation run.
            config:         ConfigState at end of run.
            duration_hours: Simulated horizon length.
            cw_busy_time:   List of individual CW phase durations.
            mw_busy_time:   List of individual MW cycle sub-durations.
            robot_busy:     List of individual robot phase durations.
            generated:      Total products generated by arrival process.
            dropped:        Products lost due to buffer overflow.

        Returns:
            Dict of KPI name → scalar value.
        """
        sim_duration_s = duration_hours * 3600.0

        # ── Products processed ─────────────────────────────────────────
        cw_products = {tr.product_id for tr in task_log if tr.workstation == "CW"
                       and tr.task_label == "05_pick_leave"}
        mw_products = {tr.product_id for tr in task_log if tr.workstation == "MW"
                       and tr.task_label == "07_bag_leave"}
        total_units = len(mw_products)  # fully completed units
        throughput  = total_units / duration_hours if duration_hours > 0 else 0.0

        # ── CW cycle time (sum of all 5 phases per product) ───────────
        cw_cycles: Dict[int, List[TaskRecord]] = defaultdict(list)
        for tr in task_log:
            if tr.workstation == "CW":
                cw_cycles[tr.product_id].append(tr)

        cw_cycle_times = []
        for pid, phases in cw_cycles.items():
            if len(phases) == len(CW_TASK_SEQUENCE):
                ct = sum(p.phase_duration for p in phases)
                cw_cycle_times.append(ct)

        # ── MW cycle time ──────────────────────────────────────────────
        mw_cycles: Dict[int, List[TaskRecord]] = defaultdict(list)
        for tr in task_log:
            if tr.workstation == "MW":
                mw_cycles[tr.product_id].append(tr)

        mw_cycle_times = []
        for pid, phases in mw_cycles.items():
            if len(phases) == len(MW_TASK_SEQUENCE):
                ct = sum(p.phase_duration for p in phases)
                mw_cycle_times.append(ct)

        # ── Utilisation ───────────────────────────────────────────────
        cw_total_busy  = sum(cw_busy_time)
        mw_total_busy  = sum(mw_busy_time)
        robot_total_busy = sum(robot_busy)

        cw_util   = (cw_total_busy / sim_duration_s)  if sim_duration_s > 0 else 0.0
        mw_util   = (mw_total_busy / sim_duration_s)  if sim_duration_s > 0 else 0.0
        robot_util= (robot_total_busy / sim_duration_s) if sim_duration_s > 0 else 0.0

        # ── Buffer wait times ─────────────────────────────────────────
        buffer_waits = [tr.queue_wait_time for tr in task_log
                        if tr.task_label == "01_pick_fix1"]
        mw_waits     = [tr.queue_wait_time for tr in task_log
                        if tr.task_label == "06_filter_assembly"]

        # ── Physiological KPIs ────────────────────────────────────────
        cw_physio = [pr for pr in physio_log if pr.workstation == "CW"]
        mw_physio = [pr for pr in physio_log if pr.workstation == "MW"]

        cw_hr = [pr.hr_bpm for pr in cw_physio] or [0.0]
        mw_hr = [pr.hr_bpm for pr in mw_physio] or [0.0]

        # Physiological Load Index (PLI):
        # PLI = Σ (HR_task - HR_ctrl) × phase_duration_minutes
        # For each physiological record, compute excess HR above CTRL baseline.
        # Reference: Kilbom (1990), Ergonomics 33(9):1163-1185.
        ctrl_cw = PHYSIO_CTRL_HR.get(config.cw_worker_id, 82.0)
        ctrl_mw = PHYSIO_CTRL_HR.get(config.mw_worker_id, 82.0)

        pli_cw = sum(max(pr.hr_bpm - ctrl_cw, 0.0) * (pr.phase_duration / 60.0)
                     for pr in cw_physio)
        pli_mw = sum(max(pr.hr_bpm - ctrl_mw, 0.0) * (pr.phase_duration / 60.0)
                     for pr in mw_physio)

        fatigue_scores = [pr.fatigue_score for pr in physio_log] or [0.0]

        # CW robot-wait fraction (time in robot phases / total CW time)
        robot_phase_duration = sum(tr.phase_duration for tr in task_log
                                   if tr.workstation == "CW" and tr.is_robot_phase)
        cw_idle_fraction = (robot_phase_duration / cw_total_busy
                            if cw_total_busy > 0 else 0.0)

        # ── Lean KPIs ─────────────────────────────────────────────────
        # OEE = Availability × Performance × Quality
        # Availability: fraction of time at least one station is productive.
        # Performance : actual throughput / maximum theoretical throughput.
        # Quality     : (total_units - dropped) / total_units; dropped = overflow.
        availability    = min((cw_util + mw_util) / 2.0 + 0.05, 1.0)  # conservative proxy
        max_theoretical = sim_duration_s / config.takt_time_seconds
        performance     = min(total_units / max_theoretical, 1.0) if max_theoretical > 0 else 0.0
        quality         = ((total_units) / (total_units + dropped)
                           if (total_units + dropped) > 0 else 1.0)
        oee             = availability * performance * quality

        # Line balance ratio = min station time / max station time
        mean_cw = float(np.mean(cw_cycle_times)) if cw_cycle_times else 1.0
        mean_mw = float(np.mean(mw_cycle_times)) if mw_cycle_times else 1.0
        line_balance = min(mean_cw, mean_mw) / max(mean_cw, mean_mw, 1e-9)

        # Takt adherence = takt / bottleneck cycle time (capped at 1.0)
        bottleneck_ct  = max(mean_cw, mean_mw)
        takt_adherence = min(config.takt_time_seconds / bottleneck_ct, 1.0) if bottleneck_ct > 0 else 1.0

        return {
            # Operational
            "total_units_produced":        total_units,
            "total_units_generated":       generated,
            "total_units_dropped":         dropped,
            "throughput_units_per_hour":   round(throughput, 3),
            "cw_mean_cycle_time_s":        round(float(np.mean(cw_cycle_times)) if cw_cycle_times else 0.0, 2),
            "cw_std_cycle_time_s":         round(float(np.std(cw_cycle_times))  if cw_cycle_times else 0.0, 2),
            "mw_mean_cycle_time_s":        round(float(np.mean(mw_cycle_times)) if mw_cycle_times else 0.0, 2),
            "mw_std_cycle_time_s":         round(float(np.std(mw_cycle_times))  if mw_cycle_times else 0.0, 2),
            "cw_utilisation_pct":          round(cw_util   * 100, 2),
            "mw_utilisation_pct":          round(mw_util   * 100, 2),
            "robot_utilisation_pct":       round(robot_util * 100, 2),
            "mean_buffer_wait_s":          round(float(np.mean(buffer_waits)) if buffer_waits else 0.0, 3),
            "max_buffer_wait_s":           round(float(np.max(buffer_waits))  if buffer_waits else 0.0, 3),
            "mean_mw_buffer_wait_s":       round(float(np.mean(mw_waits)) if mw_waits else 0.0, 3),
            # Physiological / Ergonomic
            "cw_mean_hr_bpm":              round(float(np.mean(cw_hr)), 2),
            "cw_std_hr_bpm":              round(float(np.std(cw_hr)),  2),
            "cw_peak_hr_bpm":              round(float(np.max(cw_hr)), 2),
            "mw_mean_hr_bpm":              round(float(np.mean(mw_hr)), 2),
            "mw_std_hr_bpm":             round(float(np.std(mw_hr)),  2),
            "mw_peak_hr_bpm":              round(float(np.max(mw_hr)), 2),
            "pli_cw":                      round(pli_cw, 3),
            "pli_mw":                      round(pli_mw, 3),
            "mean_fatigue_score":          round(float(np.mean(fatigue_scores)), 4),
            "peak_fatigue_score":          round(float(np.max(fatigue_scores)), 4),
            "cw_idle_fraction":            round(cw_idle_fraction, 4),
            # Lean
            "oee":                         round(oee, 4),
            "line_balance_ratio":          round(line_balance, 4),
            "takt_adherence":              round(takt_adherence, 4),
        }


# ─────────────────────────────────────────────────────────────────────────────
